# Nixpacks configuration for Railway
# Deploy Python API only, ignore Next.js frontend

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPkgs = []

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "cd api && python3.11 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
