# Nixpacks configuration for Railway
# Deploy Python API only

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
