# Nixpacks configuration for Railway
# Deploy Python API only - Disable Node.js detection

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["echo 'Skipping Node.js build - Python API only'"]

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
